### PR TITLE
feat: kill-process

### PR DESCRIPTION
**Pull request by tomonarifeehan**
Changes Made:

Added endpoint: /kill-training-process
Added endpoint: /kill-testing-process
Updated UI to show/hide Train/Stop Train and Test / Stop Test based on /ping response

### CODE REVIEW

**Comment by tomonarifeehan** [comment]
Screenshot 2024-06-18 at 10 16 34 PM

**Comment by tomonarifeehan** [comment]
@MintOwlTech I added Training / Testing check to
`@app.route('/ping', methods=['GET'])`

and show/hide based on response:
`return jsonify({ "message": "pong", "trainingInProgress": trainingInProgress, "testingInProgress": testingInProgress }), 200`

However, it is throwing some weird AccessDeniedError for me right now. Will look again later.

Screenshot 2024-06-18 at 11 56 59 PM

**Comment by MintOwlTech** [comment]
When I run it it doesn't throw an error. However, it also doesn't return true even when a training is running. 

image

**Comment by MintOwlTech** [comment]
As soon as it works, it would be a bit cleaner if the ping function is only called once. So either in the Header or in the Experiment Builder. If that is too much of a hassle to pass down the values. Maybe a seperate request is better.

**Pull request merged**
