### PR TITLE
feat: kill-process-train-test

### PR DESCRIPTION
**Pull request by tomonarifeehan**
Changes Made:
- Added endpoint: /kill-training-process
- Added endpoint: /kill-testing-process
- Updated UI to toggle Play/Stop icon

**TO DO:**
- I couldn't figure out how to change the state to show/hide button and also call SetFieldValue(). code below wasn't working

```
onClick = { () => { setTrainingInProgress(true); setFieldValue("submitType", "training") } }
onClick = { () => { setTestingInProgress(true); setFieldValue("submitType", "testing") } }
```

- Test endpoints to see if it actually works.

https://github.com/ReproModel/repromodel/assets/20110627/eb49c324-dea7-423d-bfff-d005d4a373b8

https://github.com/ReproModel/repromodel/assets/20110627/b9efe6ba-3a3e-4257-a129-0f4f0a6c5c27

### CODE REVIEW

**Comment by tomonarifeehan** [comment]
@MintOwlTech @dsitnik I'm stuck haha

I don't know how to test this.

**DemoTrainingConfig.json** is not working for me.

Screenshot_2024-06-13_at_6 14 23_PM

**Comment by dsitnik** [comment]
@tomonarifeehan try with `train_config.json` saved in `repromodel_code` folder. The current version should work. 

It can be our DemoTrainingConfig.json in the future. I will make one Demo config with our newly implemented datasets and models tomorrow.

**Comment by dsitnik** [comment]
@tomonarifeehan Found the bug! It didn't work because the "probability" parameter in config files was int, but it is enforced to be float. I changed the decorator to automatically cast to float. Also added some additional error logging.

Everything is already merged into the dev branch. The functionality of killing the processes didn't work for me, though.

**Comment by MintOwlTech** [comment]
> @tomonarifeehan try with `train_config.json` saved in `repromodel_code` folder. The current version should work.
> 
> It can be our DemoTrainingConfig.json in the future. I will make one Demo config with our newly implemented datasets and models tomorrow.

These are the same files. When it is downloaded it picks the train_config.json. It just names it more descriptive for the user in the download.

**Comment by MintOwlTech** [comment]
@tomonarifeehan I played around with the onClick but also didn't got it working. Apparently the other function interferes with the standard form submission. 
I made both buttons always visible and not used the setTrainingProcess, by that I could test the functionality and it seems to work good :) 

The solution you proposed with the switching buttons only works if the user doesn't refresh the page. Which would be very likely for longer training runs. 

My proposal for you would be to check if there is a training run active in the backend and based on that show the stop training button or not. 

You could combine that into the ping function (that checks if the backend is up and running). By adding something like that: 
(1 min ChatGPT search) 
def is_process_running(process_name):
    for proc in psutil.process_iter(['pid', 'name', 'cmdline']):
        if process_name in proc.info['cmdline']:
            return True
    return False

process_name = 'trainer.py'


Then we could update the status checks to show two more components for Training and Testing. 
image

What do you think?

**Comment by MintOwlTech** [comment]
> > @tomonarifeehan try with `train_config.json` saved in `repromodel_code` folder. The current version should work.
> > It can be our DemoTrainingConfig.json in the future. I will make one Demo config with our newly implemented datasets and models tomorrow.
> 
> These are the same files. When it is downloaded it picks the train_config.json. It just names it more descriptive for the user in the download.

Just realized that this doesn't make sense. I make them different now. Since the demo run should be on the dummy data we let the user generate.

**Comment by tomonarifeehan** [comment]
> My proposal for you would be to check if there is a training run active in the backend and based on that show the stop training button or not.
> 
> You could combine that into the ping function (that checks if the backend is up and running). By adding something like that: (1 min ChatGPT search) def is_process_running(process_name): for proc in psutil.process_iter(['pid', 'name', 'cmdline']): if process_name in proc.info['cmdline']: return True return False
> 
> process_name = 'trainer.py'
> 
> Then we could update the status checks to show two more components for Training and Testing. image
> 
> What do you think?

Yes, I think your approach is better.

**Comment by tomonarifeehan** [comment]
I got confused trying to merge changes so I just made another branch: https://github.com/ReproModel/repromodel/pull/130

**Pull request closed without merging**
