### PR TITLE
feat: implement modality selector

### PR DESCRIPTION
**Pull request by MintOwlTech**
Now finally implemented the functionality for the filtering of models. 

Please test it. 

image

ToDo Open: 
- Find a way to show the different images for the options.

### CODE REVIEW

**Review by dsitnik — CHANGES_REQUESTED** [review]
Looks good. A few change suggestions:

- Instead of Filtered Models, put Available models (at first the number is everything that is available, and by filtering we reduce)
- Filter Datasets also (as Available Datasets)
- Add an empty line between images and the next selection
- Add different images to categories. 
- Align the button and images on the left side

**Comment by tomonarifeehan** [comment]
@MintOwlTech I made slight improvements to the UI layout. I did not like how "Skip Filter" and "Filtered Models: <x>" were placed. Code for filtering of models looks good to me.

Screenshot 2024-06-19 at 4 34 59 PM

**Comment by tomonarifeehan** [comment]
@MintOwlTech Added support for different images in:

src > components > modality-section > image-urls.jsx

Just change the image urls to whatever you want. I didn't know what to use for some of them.

Screenshot 2024-06-19 at 5 55 25 PM

**Review by tomonarifeehan — APPROVED** [review]
Looks good to me. I added minor changes to layout and support for images.

**Comment by MintOwlTech** [comment]
> Looks good. A few change suggestions:
> 
> * Instead of Filtered Models, put Available models (at first the number is everything that is available, and by filtering we reduce)
> * Filter Datasets also (as Available Datasets)
> * Add an empty line between images and the next selection
> * Add different images to categories.
> * Align the button and images on the left side

Implemented the missing things: 
For this one I do not know what is that: 
Add an empty line between images and the next selection 

But I guess it is fixed. 

The Dataset Filter I will add within phase 2. Right now there is anyway only 1 dataset with the tags mentioned.

**Review by dsitnik — APPROVED** [review]
all good, we can merge for now and just update images in one of the next iterations

**Pull request merged**
