### PR TITLE
fix: set-llm-output

### PR DESCRIPTION
**Pull request by tomonarifeehan**
Changes Made:
- set LLM output on axios.then()
- set radio buttons and LLM dropdown and additional prompt values on axios.then() because they get cleared onSubmit
- add loading animation

### CODE REVIEW

**Comment by MintOwlTech** [comment]
Nice, great that you made it work, and good that you added the loading animation. 
A few suggestions:

- make the loading animation cover only the Editor (and maybe the submit button as well). Not the complete component. 
- We can hide the LLM Model selector for now, or (since you made it look nice), limit it to only the option we have llama3
- The config file is not yet passed into the "runQuery", in my first version I had it hardcoded to "Method is bruteforce" since the "Setfieldvalue" had thrown an error for me. Probably need to define config as variable here again, since it is not used in a Formik context this time.

**Comment by tomonarifeehan** [comment]
Added suggested changes.

Only one Llama 3 option.
Screenshot 2024-06-08 at 3 04 48 PM

Moved loading animation to cover output and buttons only.
Screenshot 2024-06-08 at 3 01 46 PM

**Comment by tomonarifeehan** [comment]
> * The config file is not yet passed into the "runQuery", in my first version I had it hardcoded to "Method is bruteforce" since the "Setfieldvalue" had thrown an error for me. Probably need to define config as variable here again, since it is not used in a Formik context this time.

Can you finish this part? I'm unclear about what needs to be done.

**Comment by MintOwlTech** [comment]
> > * The config file is not yet passed into the "runQuery", in my first version I had it hardcoded to "Method is bruteforce" since the "Setfieldvalue" had thrown an error for me. Probably need to define config as variable here again, since it is not used in a Formik context this time.
> 
> Can you finish this part? I'm unclear about what needs to be done.

Already working on it :)

**Pull request merged**
