### PR TITLE
feat: first-time-modal

### PR DESCRIPTION
**Pull request by MintOwlTech**
I have fixed / modified the initial setup to allow the user to make a test run more easily. 

- fixed creation of virtual environment (directly pushed to dev) 
- changed dir_path of the generate_data, so that it can be called from the repository level
- added a "First Time here" button that launches a modal. 
- Added Modal with Simple instructions to make the backend generate Dummy Data and Download DemoConfig. 
- set fromcheckpoint: false -> let new users run the demo script

image

Bildschirmfoto 2024-06-02 um 20 59 36

### CODE REVIEW

**Comment by MintOwlTech** [comment]
What do you think of this? 
In the modal we can also then link the docs.

**Comment by tomonarifeehan** [comment]
@MintOwlTech 

Modal looks really good.

Few Suggestions:
- Pass in trainConfig as parameter to function "const handleDownload = ()" and move it to shared **utils** folder so it can be reused in the **CustomScript** component
- Move **FirstTimeModal** component outside of header folder into its own folder **components > first-time-modal**

**Review by tomonarifeehan — CHANGES_REQUESTED** [review]
@MintOwlTech 

Modal looks really good.

Few Suggestions:
- Pass in trainConfig, output filename, and type "json" as parameters to function "const handleDownload = ()" and move it to shared **utils** folder so it can be reused in the **CustomScript** component
- Move **FirstTimeModal** component and css outside of **header** folder into its own folder **components > first-time-modal**
- Capitalize "repromodel" to "ReproModel" in 2nd text. Capitalize "Repromodel" to "ReproModel" in 5th text

Few spots where you have double model in jsx:

 aria-labelledby="modal-modal-title"
 aria-describedby="modal-modal-description"
 <Typography id="modal-modal-title" 
 <Typography id="modal-modal-description"

**Comment by MintOwlTech** [comment]
@tomonarifeehan thanks for the hints. Implemented all of them.

**Comment by tomonarifeehan** [comment]
@MintOwlTech 

Also, one more thing I missed. Maybe add a close button 'x' to top right of modal?

**Review by tomonarifeehan — APPROVED** [review]
LGTM.

**Pull request merged**
